# Generated by Django 4.2.6 on 2023-10-10 22:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lysbl_api', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='addons',
        ),
        migrations.AlterModelOptions(
            name='account',
            options={'verbose_name': 'account', 'verbose_name_plural': 'account'},
        ),
        migrations.AlterModelOptions(
            name='brows',
            options={'verbose_name': 'brow', 'verbose_name_plural': 'brows'},
        ),
        migrations.AlterModelOptions(
            name='giftcards',
            options={'verbose_name': 'giftcard', 'verbose_name_plural': 'giftcards'},
        ),
        migrations.AlterModelOptions(
            name='lashes',
            options={'verbose_name': 'lash', 'verbose_name_plural': 'lashes'},
        ),
        migrations.AlterModelOptions(
            name='make_up',
            options={'verbose_name': 'make_up', 'verbose_name_plural': 'make_ups'},
        ),
        migrations.AlterModelOptions(
            name='nails',
            options={'verbose_name': 'nail', 'verbose_name_plural': 'nails'},
        ),
        migrations.AlterModelOptions(
            name='orders',
            options={'verbose_name': 'order', 'verbose_name_plural': 'orders'},
        ),
        migrations.AlterModelOptions(
            name='skincare',
            options={'verbose_name': 'skincare', 'verbose_name_plural': 'skincares'},
        ),
        migrations.AlterModelOptions(
            name='spray_tans',
            options={'verbose_name': 'spray_tan', 'verbose_name_plural': 'spray_tans'},
        ),
        migrations.AlterModelOptions(
            name='wax',
            options={'verbose_name': 'wax', 'verbose_name_plural': 'waxes'},
        ),
    ]
