# Generated by Django 4.2.6 on 2023-11-18 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lysbl_api', '0002_delete_addons_alter_account_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brows',
            name='price',
            field=models.IntegerField(verbose_name=1000),
        ),
        migrations.AlterField(
            model_name='giftcards',
            name='price',
            field=models.IntegerField(verbose_name=1000),
        ),
        migrations.AlterField(
            model_name='lashes',
            name='price',
            field=models.IntegerField(verbose_name=1000),
        ),
        migrations.AlterField(
            model_name='make_up',
            name='price',
            field=models.IntegerField(verbose_name=1000),
        ),
        migrations.AlterField(
            model_name='nails',
            name='price',
            field=models.IntegerField(verbose_name=1000),
        ),
        migrations.AlterField(
            model_name='skincare',
            name='price',
            field=models.IntegerField(verbose_name=1000),
        ),
        migrations.AlterField(
            model_name='spray_tans',
            name='price',
            field=models.IntegerField(verbose_name=1000),
        ),
        migrations.AlterField(
            model_name='wax',
            name='price',
            field=models.IntegerField(verbose_name=1000),
        ),
    ]
