# Generated by Django 4.2.7 on 2023-12-22 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lysbl_api', '0003_alter_brows_price_alter_giftcards_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brows',
            name='price',
            field=models.IntegerField(default=1000),
        ),
        migrations.AlterField(
            model_name='giftcards',
            name='price',
            field=models.IntegerField(default=1000),
        ),
        migrations.AlterField(
            model_name='lashes',
            name='price',
            field=models.IntegerField(default=1000),
        ),
        migrations.AlterField(
            model_name='make_up',
            name='price',
            field=models.IntegerField(default=1000),
        ),
        migrations.AlterField(
            model_name='nails',
            name='price',
            field=models.IntegerField(default=1000),
        ),
        migrations.AlterField(
            model_name='skincare',
            name='price',
            field=models.IntegerField(default=1000),
        ),
        migrations.AlterField(
            model_name='spray_tans',
            name='price',
            field=models.IntegerField(default=1000),
        ),
        migrations.AlterField(
            model_name='wax',
            name='price',
            field=models.IntegerField(default=1000),
        ),
    ]
